# Generated by Django 5.0.6 on 2024-05-18 08:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_sum', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Сумма пожертвования')),
                ('donation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата пожертвования')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('reason', models.CharField(choices=[('birthday', 'День рождения'), ('wedding', 'Свадьба'), ('holiday', 'Праздник'), ('child', 'Рождение ребенка'), ('event', 'Корпоративное мероприятие')], max_length=50, verbose_name='Причина')),
                ('description', models.TextField(verbose_name='Описание')),
                ('collection_sum', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Сумма сбора')),
                ('current_sum', models.PositiveSmallIntegerField(default=0, verbose_name='Текущая сумма сбора')),
                ('people_amount', models.PositiveSmallIntegerField(default=0, verbose_name='Количество пожертвовавших людей')),
                ('image', models.ImageField(upload_to='funds_collection/images/collect', verbose_name='Обложка сбора')),
                ('finish_date', models.DateTimeField(verbose_name='Дата завершения сбора')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funds_collection', to=settings.AUTH_USER_MODEL, verbose_name='Автор группового денежного сбора')),
                ('payments', models.ManyToManyField(related_name='collects', to='funds_collection.payment', verbose_name='Лента сбора')),
            ],
        ),
    ]
