# Generated by Django 5.0.6 on 2024-05-18 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds_collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collect',
            options={'ordering': ('title',), 'verbose_name': 'сбор', 'verbose_name_plural': 'Сборы'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('id',), 'verbose_name': 'платеж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.RenameField(
            model_name='collect',
            old_name='collection_sum',
            new_name='target_sum',
        ),
        migrations.RemoveField(
            model_name='collect',
            name='payments',
        ),
        migrations.AddField(
            model_name='payment',
            name='collect',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='funds_collection.collect', verbose_name='Денежный сбор'),
            preserve_default=False,
        ),
    ]
